### ISSUE TITLE
error handling -- expression input

### ISSUE THREAD

**Issue by cmatKhan** [BrentLab/NetProphet_2.0#2]
"adding error handling" should be a general issue.

But, there should be error handling specifically around micro array vs rnaseq input -- are both expected to be logged, eg, at entry? If not, then there should be a way to check if the values are likely log values or not (maybe even just looking for float vs int?)

**Comment by cmatKhan** [comment]
(this is re: lab meeting 1/06/20 -- the "rna seq" input flag wasn't set, and micro array is default)

**Comment by yiming-kang** [comment]
The wiki clearly defines that the input gene expression data is a matrix of the log2 fold-change expression values in the samples with respect to those in wild type or control, regardless of the data generation process (being microarray or RNA-seq).

The microarray flag is an option in NP1 but not in NP2, because in the snake file for NP2, the rule for running NP1 module has -m flag set.

**Comment by sandeepacharya464** [comment]
This has been closed but I want to make it clear that the confusion we have had in past few weeks in regard to the expression input stems from the fact that the documentation was written keeping in mind that the users are going to use Yiming's interface and data input format. That has changed since Dhoha was using her self-built interface and in her interface the default case is that the data is assumed to be microarray data. And if we pass count data from RNA-Seq instead of lfc, this can possibly cause a problem since NetProphet assumes count data is microarray data which is not true. This issue has been discussed with both Yiming and Dhoha and future work will be done keeping this in mind.
